.TH MSOFFICE 1 2025-Jun "" "Excel liked theme style for ggplot"
.SH NAME
msoffice \- msoffice(
    <i>accents</i> = [<span style='color: #E7E6E6;'><strong>'#e7e6e6'</strong></span>,<span style='color: #5B9BD5;'><strong>'#5b9bd5'</strong></span>,<span style='color: #ED7D31;'><strong>'#ed7d31'</strong></span>,<span style='color: #A5A5A5;'><strong>'#a5a5a5'</strong></span>,<span style='color: #FFC000;'><strong>'#ffc000'</strong></span>,<span style='color: #4472C4;'><strong>'#4472c4'</strong></span>,<span style='color: #70AD47;'><strong>'#70ad47'</strong></span>])
.SH SYNOPSIS
\fImsoffice(
    <i>accents</i> = [<span style='color: #E7E6E6;'><strong>'#e7e6e6'</strong></span>,<span style='color: #5B9BD5;'><strong>'#5b9bd5'</strong></span>,<span style='color: #ED7D31;'><strong>'#ed7d31'</strong></span>,<span style='color: #A5A5A5;'><strong>'#a5a5a5'</strong></span>,<span style='color: #FFC000;'><strong>'#ffc000'</strong></span>,<span style='color: #4472C4;'><strong>'#4472c4'</strong></span>,<span style='color: #70AD47;'><strong>'#70ad47'</strong></span>])\fR
.SH OPTIONS
.PP
\fBaccents\fB \fR\- ['#44546a', '#e7e6e6', '#5b9bd5', '#ed7d31', '#a5a5a5', '#ffc000', '#4472c4', '#70ad47']. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.msoffice at msoffice.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
