.TH MSOFFICE 1 2024-May "" "Excel liked theme style for ggplot"
.SH NAME
msoffice \- msoffice(
    <i>accents</i> = [])
.SH SYNOPSIS
\fImsoffice(
    <i>accents</i> = [])\fR
.SH OPTIONS
.PP
\fBaccents\fB \fR\- [#44546a, #e7e6e6, #5b9bd5, #ed7d31, #a5a5a5, #ffc000, #4472c4, #70ad47]. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.msoffice at msoffice.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
