.TH THEME_LIGHT 1 2025-Sep "" "theme_light"
.SH NAME
theme_light \- theme_light(
    <i>axis.text</i> = <span style='color: blue !important;'>NULL</span>,
    <i>axis.title</i> = <span style='color: blue !important;'>NULL</span>,
    <i>legend.tick</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fItheme_light(
    <i>axis.text</i> = <span style='color: blue !important;'>NULL</span>,
    <i>axis.title</i> = <span style='color: blue !important;'>NULL</span>,
    <i>legend.tick</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBaxis.text\fB \fR\- NULL. 
.PP
.PP
\fBaxis.title\fB \fR\- NULL. 
.PP
.PP
\fBlegend.tick\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.theme_light at default.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
