.\" man page create by R# package system.
.TH GGRAPH 1 2000-01-01 "geom_node_convexHull" "geom_node_convexHull"
.SH NAME
geom_node_convexHull \- 
.SH SYNOPSIS
\fIgeom_node_convexHull(\fBmapping\fR as <generic> ggplotReader = \fB<NULL>\fR, 
\fBalpha\fR as double = 1, 
\fBscale\fR as double = 1.125, 
\fBstroke_width\fR as double = 3, 
\fBspline\fR as double = 0);\fR
.SH SEE ALSO
ggraph
.SH FILES
.PP
ggraph.dll
.PP
