.\" man page create by R# package system.
.TH GGRAPH 1 2000-01-01 "geom_node_point" "geom_node_point"
.SH NAME
geom_node_point \- 
.SH SYNOPSIS
\fIgeom_node_point(\fBmapping\fR as any = CALL "AES"(), 
\fBdefaultColor\fR as any = "SteelBlue", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggraph
.SH FILES
.PP
ggraph.dll
.PP
