.\" man page create by R# package system.
.TH GGRAPH 1 2000-1月 "geom_node_text" "geom_node_text"
.SH NAME
geom_node_text \- 
.SH SYNOPSIS
\fIgeom_node_text(\fBmapping\fR as any = CALL "AES"(), 
\fBiteration\fR as integer = -1, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggraph
.SH FILES
.PP
ggraph.dll
.PP
