.\" man page create by R# package system.
.TH GGRAPH 1 2000-Jan "geom_edge_link" "geom_edge_link"
.SH NAME
geom_edge_link \- 
.SH SYNOPSIS
\fIgeom_edge_link(\fBmapping\fR as any = CALL "AES"(), 
\fBcolor\fR as any = "lightgray", 
\fBwidth\fR as any = "2,5", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggraph
.SH FILES
.PP
ggraph.dll
.PP
