.\" man page create by R# package system.
.TH GGRAPH 1 2000-Jan "map" "map"
.SH NAME
map \- create style mapping for do graph rendering
.SH SYNOPSIS
\fImap(\fBkey\fR as string, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create style mapping for do graph rendering
.PP
.SH OPTIONS
.PP
\fBkey\fB \fR\- the graph data property name key. 
.PP
.PP
\fBvals\fB \fR\- mapping values. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ggraph
.SH FILES
.PP
ggraph.dll
.PP
