.\" man page create by R# package system.
.TH GGFORCE 1 2000-01-01 "layout_springembedder" "layout_springembedder"
.SH NAME
layout_springembedder \- 
.SH SYNOPSIS
\fIlayout_springembedder(\fBcanvas\fR as any, 
\fBiterations\fR as integer = 100, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggforce
.SH FILES
.PP
ggraph.dll
.PP
