.\" man page create by R# package system.
.TH GGFORCE 1 2000-01-01 "layout_springforce" "layout_springforce"
.SH NAME
layout_springforce \- 
.SH SYNOPSIS
\fIlayout_springforce(\fBstiffness\fR as double = 80, 
\fBrepulsion\fR as double = 4000, 
\fBdamping\fR as double = 0.83, 
\fBiterations\fR as integer = 1000);\fR
.SH SEE ALSO
ggforce
.SH FILES
.PP
ggraph.dll
.PP
