.\" man page create by R# package system.
.TH GGFORCE 1 2000-1月 "layout_springforce" "layout_springforce"
.SH NAME
layout_springforce \- 
.SH SYNOPSIS
\fIlayout_springforce(\fBstiffness\fR as double = 50000, 
\fBrepulsion\fR as double = 100, 
\fBdamping\fR as double = 0.9, 
\fBiterations\fR as integer = 1000, 
\fBtime_step\fR as double = 0.0001);\fR
.SH SEE ALSO
ggforce
.SH FILES
.PP
ggraph.dll
.PP
