.\" man page create by R# package system.
.TH GGFORCE 1 2000-Jan "layout_forcedirected" "layout_forcedirected"
.SH NAME
layout_forcedirected \- 
.SH SYNOPSIS
\fIlayout_forcedirected(\fBejectFactor\fR as integer = 6, 
\fBcondenseFactor\fR as integer = 3, 
\fBmaxtx\fR as integer = 4, 
\fBmaxty\fR as integer = 3, 
\fBdist_threshold\fR as any = "30,250", 
\fBsize\fR as any = "1000,1000", 
\fBiterations\fR as integer = 20000, 
\fBtime_step\fR as double = 1E-05, 
\fBalgorithm\fR as any = ["force_directed","degree_weighted","group_weighted","edge_weighted"], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggforce
.SH FILES
.PP
ggraph.dll
.PP
