.\" man page create by R# package system.
.TH GGPUBR 1 2000-Jan "geom_text_repel" "geom_text_repel"
.SH NAME
geom_text_repel \- 
.SH SYNOPSIS
\fIgeom_text_repel(\fBmapping\fR as <generic> ggplotReader = \fB<NULL>\fR, 
\fBdata\fR as any = \fB<NULL>\fR, 
\fBstat\fR as string = "identity", 
\fBposition\fR as string = "identity", 
\fBparse\fR as boolean = FALSE, 
\fBnudge_x\fR as double = 0, 
\fBnudge_y\fR as double = 0, 
\fBna_rm\fR as boolean = FALSE, 
\fBshow_legend\fR as boolean = FALSE, 
\fBinherit_aes\fR as boolean = TRUE, 
\fBcolor\fR as any = "steelblue", 
\fBwhich\fR as <generic> Expression = \fB<NULL>\fR, 
\fBalpha\fR as double = 1, 
\fBsize\fR as <generic> Single = \fB<NULL>\fR, 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggpubr
.SH FILES
.PP
ggpubr.dll
.PP
