.\" man page create by R# package system.
.TH GGPUBR 1 2000-Jan "stat_ellipse" "stat_ellipse"
.SH NAME
stat_ellipse \- 
.SH SYNOPSIS
\fIstat_ellipse(\fBdata\fR as any = \fB<NULL>\fR, 
\fBcolor\fR as any = \fB<NULL>\fR, 
\fBlevel\fR as double = 0.95, 
\fBalpha\fR as double = 0.6);\fR
.SH SEE ALSO
ggpubr
.SH FILES
.PP
ggpubr.dll
.PP
